server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.113:3306/orangesoft?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: orangesoft
    password: orangesoft

mybatis:
  type-aliases-package: com.orangeSoft.market.pojo
  mapper-locations: classpath:mybatis/mapping/*Mapper.xml,classpath:mybatis/mapping/*MapperE.xml

logging:
  level:
    com.orangeSoft.market.mapper: debug  # 打印sql语句